[package]
name = "message_generator_sv2"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.8.0"
binary_sv2 = { version = "1.0.0", features = ["with_serde"] }
codec_sv2 = { version = "1.0.0", features = ["noise_sv2","with_buffer_pool","with_serde"] }
const_sv2 = { version = "1.0.0" }
load_file = "1.0.1"
network_helpers_sv2 = { version = "2.0.0", features = ["with_tokio","with_serde"] }
roles_logic_sv2 = { version = "1.0.0", features = ["with_serde"] }
v1 = { version = "^1.0.0", package="sv1_api" }
serde = { version = "*", features = ["derive", "alloc"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tokio = { version = "1", features = ["full"] }
arbitrary = { version = "1", features = ["derive"] }
rand = "0.8.5"
secp256k1 = "0.28.2"
key-utils = "1.1.0"
tracing = { version = "0.1" }
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
tracing-core = "*"
